// 轮播图
export const CHANGE_TOP_BANNER = "CHANGE_TOP_BANNER";

// 热门推荐
export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND";
export const HOT_RECOMMEND_LIMIT = 8;

// 新碟推荐
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";
export const NEW_ALBUM_LIMIT = 15;

// 榜单
export const CHAGE_TOP_LIST = "CHAGE_TOP_LIST";
export const CHAGE_TOP_LIST_DETAIL = "CHAGE_TOP_LIST_DETAIL";
export const CHAGE_NEW_LIST_DETAIL = "CHAGE_NEW_LIST_DETAIL";
export const CHAGE_ORIGIN_LIST_DETAIL = "CHAGE_ORIGIN_LIST_DETAIL";
